databaseType = "PostgreSql"
id = "fb5893b6-dae1-4767-a0d8-e864847eb7f9"
name = "libDB"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.target1]
url = "jdbc:postgresql://localhost:5444/librarydb"
schemas = [ "public" ]
displayName = "Lib_System"
